image: $CI_SERVER_HOST:4567/libretro/infrastructure/libretro-build-libnx-devkitpro:latest

variables:
  PACKAGE_FOLDER: "sys-clk"

stages:
  - package

nightly:
  stage: package
  script:
    - bash build.sh $PACKAGE_FOLDER
  artifacts:
    name: $PACKAGE_FOLDER
    expire_in: 24 hours
    paths:
    - $PACKAGE_FOLDER
